### ISSUE TITLE
Failing test cases

### ISSUE THREAD

**Issue by fevangelista** [evangelistalab/forte#7] opened 2016-08-10 02:57 UTC
The following test cases fail on my laptop with commit f07391b121504bb354cefc701283e4e832391da9 

```
    CASSCF-3..................................................DOES NOT MATCH
    CASSCF-4..................................................DOES NOT MATCH
    CASSCF-5..................................................DOES NOT MATCH
    MR-DSRG-PT2-1.............................................DOES NOT MATCH
    DSRG-MRPT2-6..............................................DOES NOT MATCH
```

Can anyone confirm this?

Here is a task list to check progress on this issue
- [X] Fix CASSCF-3
- [X] Fix CASSCF-4
- [X] Fix CASSCF-5
- [ ] Fix MR-DSRG-PT2-1
- [ ] Fix DSRG-MRPT2-6

**Comment by jeffschriber** [comment] 2016-08-10 13:41
The CASSCF cases had "import forte_parallel" instead of "import forte".

The DSRG-MRPT2-6 gave a seg fault after the MCSCF iterations. However, I ran it again a few times, and the tests pass. not sure where the error is.

I do not reproduce an error for MR-DSRG-PT2-1

**Comment by fevangelista** [comment] 2016-08-10 14:10
On my laptop both MR-DSRG-PT2-1 and DSRG-MRPT2-6 fail in forte due to DPD:

```
RuntimeError:
Fatal Error: Attempting to initilize new DPD instance before the old one was freed.
Error occurred in file: /Users/francesco/Source/psi4/src/lib/libdpd/init.cc on line: 70
The most recent 5 function calls were:
```

**Comment by jeffschriber** [comment] 2016-08-10 15:16
I don't see that error, but the backtrace does show the error sometimes at Matrix::free(). Other times, it appears in some deleting functions in boost. 

For what it's worth, I only see the error with scf_type set as out_of_core.

**Comment by kannon92** [comment] 2016-08-10 16:13
I tend to think that the DPD error might be related to PSI4 not correctly closing everything down.  I sometimes get that error, but I usually just re run the code and it goes away.

It might be a shared pointer not being deleted or something.

**Comment by lcyyork** [comment] 2016-08-15 19:42
I cannot reproduce these errors, but there are some problems with Psi4's CASSCF, which both MR-DSRG-PT2-1 and DSRG-MRPT2-6 use. Sometimes the CASSCF code suddenly jump to a NAN and stops with a Matrix::Power() problem. I assume the multi-state examples DSRG-MRPT2-8 and DSRG-MRPT3-5 have the same problem. But if the CASSCF passes, the DSRG part should work just fine.

**Comment by fevangelista** [comment] 2016-08-15 19:57
Should we open an issue on psi4's github page and post some examples?

**Comment by lcyyork** [comment] 2016-08-15 20:15
Sure, but before posting the issue, can somebody try the following input?
```
molecule {
  0 1
  BE        0.000000000000     0.000000000000     0.000000000000
  H         0.000000000000     1.270400000000     2.760000000000
  H         0.000000000000    -1.270400000000     2.760000000000
  units bohr
  no_reorient
}

set globals{
  reference           rhf
  scf_type            out_of_core
  d_convergence       12
  e_convergence       15
  docc                [2,0,0,1]
  restricted_docc     [2,0,0,0]
  active              [1,0,0,1]
  mcscf_r_convergence 8
  mcscf_e_convergence 12
  mcscf_maxiter       250
  mcscf_diis_start    6
  num_roots           2
  follow_root         1
  avg_states          [1,2]
}

basis {
spherical
****
Be     0
S   6   1.00
   1267.070000     0.001940
    190.356000     0.014786
     43.295900     0.071795
     12.144200     0.236348
      3.809230     0.471763
      1.268470     0.355183
S   3   1.00
      5.693880    -0.028876
      1.555630    -0.177565
      0.171855     1.071630
S   1   1.00
      0.057181     1.000000
P   2   1.00
      1.555630     0.144045
      0.171855     0.949692
P   1   1.00
      5.693880     1.000000
****
H      0
S   3   1.00
     19.240600     0.032828
      2.899200     0.231208
      0.653400     0.817238
S   1   1.00
      0.177600     1.000000
****
}

Ecas, wfn = energy('casscf', return_wfn=True)
```
I  tried 4 times and the CASSCF iterations are the following:
__run1__
```
   ==> Starting MCSCF iterations <==

                        Total Energy        Delta E      RMS Grad   NCI

   @MCSCF Iter   1:  -15.48622438855255    3.3392e-02   5.6141e-02   1   Initial CI
   @MCSCF Iter   2:  -15.50110691135285   -1.4883e-02   1.3782e-02   1   APPROX
   @MCSCF Iter   3:  -15.50334998105869   -2.2431e-03   6.2876e-03   1   APPROX
   @MCSCF Iter   4:  -15.50383175864421   -4.8178e-04   3.0556e-03   1   APPROX
   @MCSCF Iter   5:  -15.50393961054233   -1.0785e-04   1.4760e-03   1   APPROX
   @MCSCF Iter   6:  -15.50396390550718   -2.4295e-05   7.1214e-04   1   APPROX
   @MCSCF Iter   7:  -15.50396940788561   -5.5024e-06   3.4415e-04   1   APPROX
   @MCSCF Iter   8:  -15.50397066792286   -1.2600e-06   1.6739e-04   1   APPROX, DIIS
   @MCSCF Iter   9:    nan   nan  nan  12   APPROX, DIIS
```
__run2__
```
   ==> Starting MCSCF iterations <==

                        Total Energy        Delta E      RMS Grad   NCI

   @MCSCF Iter   1:  -15.48622438855254    3.3392e-02   5.6141e-02   1   Initial CI
   @MCSCF Iter   2:  -15.50110691135284   -1.4883e-02   1.3782e-02   1   APPROX
   @MCSCF Iter   3:  -15.50334998105868   -2.2431e-03   6.2876e-03   1   APPROX
   @MCSCF Iter   4:  -15.50383175864419   -4.8178e-04   3.0556e-03   1   APPROX
   @MCSCF Iter   5:  -15.50393961054232   -1.0785e-04   1.4760e-03   1   APPROX
   @MCSCF Iter   6:  -15.50396390550717   -2.4295e-05   7.1214e-04   1   APPROX
   @MCSCF Iter   7:  -15.50396940788560   -5.5024e-06   3.4415e-04   1   APPROX
   @MCSCF Iter   8:  -15.50397066792285   -1.2600e-06   1.6739e-04   1   APPROX, DIIS
   @MCSCF Iter   9:  -15.50397105202731   -3.8410e-07   1.1147e-05   1   APPROX, DIIS
   @MCSCF Iter  10:  -15.50397105396176   -1.9344e-09   6.1564e-07   1   APPROX, DIIS
   @MCSCF Iter  11:  -15.50397105396463   -2.8724e-12   9.7940e-08   1   APPROX, DIIS
   @MCSCF Iter  12:  -15.50397105396472   -9.4147e-14   1.3125e-08   1   APPROX, DIIS
   @MCSCF Iter  13:  -15.50397105396472    0.0000e+00   2.2830e-09   1   APPROX, DIIS
```
__run3__
```
   ==> Starting MCSCF iterations <==

                        Total Energy        Delta E      RMS Grad   NCI

   @MCSCF Iter   1:    nan   nan  nan  12   Initial CI
   @MCSCF Iter   2:    nan   nan  nan  12   APPROX
   @MCSCF Iter   3:    nan   nan  nan  12   APPROX
   @MCSCF Iter   4:    nan   nan  nan  12   APPROX
   @MCSCF Iter   5:    nan   nan  nan  12   APPROX
   @MCSCF Iter   6:    nan   nan  nan  12   APPROX
   @MCSCF Iter   7:    nan   nan  nan  12   APPROX
   @MCSCF Iter   8:    nan   nan  nan  12   APPROX, DIIS
```
__run4__
```
   ==> Starting MCSCF iterations <==

                        Total Energy        Delta E      RMS Grad   NCI

   @MCSCF Iter   1:  -15.48622438855253    3.3392e-02   5.6141e-02   1   Initial CI
   @MCSCF Iter   2:  -15.50110691135285   -1.4883e-02   1.3782e-02   1   APPROX
   @MCSCF Iter   3:  -15.50334998105870   -2.2431e-03   6.2876e-03   1   APPROX
   @MCSCF Iter   4:  -15.50383175864421   -4.8178e-04   3.0556e-03   1   APPROX
   @MCSCF Iter   5:  -15.50393961054233   -1.0785e-04   1.4760e-03   1   APPROX
   @MCSCF Iter   6:    nan   nan  nan  12   APPROX
   @MCSCF Iter   7:    nan   nan  nan  12   APPROX
   @MCSCF Iter   8:    nan   nan  nan  12   APPROX, DIIS
```
Changing the `scf_type` to `pk` does not always help as shown the following 3 runs
__pk run1__
```
   ==> Starting MCSCF iterations <==

                        Total Energy        Delta E      RMS Grad   NCI

   @MCSCF Iter   1:  -15.48622438855254    3.3392e-02   5.6141e-02   1   Initial CI
   @MCSCF Iter   2:  -15.50110691135284   -1.4883e-02   1.3782e-02   1   APPROX
   @MCSCF Iter   3:  -15.50334998105868   -2.2431e-03   6.2876e-03   1   APPROX
   @MCSCF Iter   4:  -15.50383175864419   -4.8178e-04   3.0556e-03   1   APPROX
   @MCSCF Iter   5:  -15.50393961054232   -1.0785e-04   1.4760e-03   1   APPROX
   @MCSCF Iter   6:  -15.50396390550716   -2.4295e-05   7.1214e-04   1   APPROX
   @MCSCF Iter   7:  -15.50396940788559   -5.5024e-06   3.4415e-04   1   APPROX
   @MCSCF Iter   8:  -15.50397066792285   -1.2600e-06   1.6739e-04   1   APPROX, DIIS
   @MCSCF Iter   9:  -15.50397105202731   -3.8410e-07   1.1147e-05   1   APPROX, DIIS
   @MCSCF Iter  10:  -15.50397105396175   -1.9344e-09   6.1564e-07   1   APPROX, DIIS
   @MCSCF Iter  11:  -15.50397105396462   -2.8706e-12   9.7940e-08   1   APPROX, DIIS
   @MCSCF Iter  12:  -15.50397105396471   -8.8818e-14   1.3125e-08   1   APPROX, DIIS
   @MCSCF Iter  13:  -15.50397105396472   -1.0658e-14   2.2830e-09   1   APPROX, DIIS
```
__pk run2__
```
   ==> Starting MCSCF iterations <==

                        Total Energy        Delta E      RMS Grad   NCI

   @MCSCF Iter   1:  -15.48622438855255    3.3392e-02   5.6141e-02   1   Initial CI
   @MCSCF Iter   2:  -15.50110691135284   -1.4883e-02   1.3782e-02   1   APPROX
   @MCSCF Iter   3:  -15.50334998105869   -2.2431e-03   6.2876e-03   1   APPROX
   @MCSCF Iter   4:    nan   nan  nan  12   APPROX
   @MCSCF Iter   5:    nan   nan  nan  12   APPROX
   @MCSCF Iter   6:    nan   nan  nan  12   APPROX
   @MCSCF Iter   7:    nan   nan  nan  12   APPROX
   @MCSCF Iter   8:    nan   nan  nan  12   APPROX, DIIS
```
__pk run3__
```
   ==> Starting MCSCF iterations <==

                        Total Energy        Delta E      RMS Grad   NCI

   @MCSCF Iter   1:  -15.48622438855254    3.3392e-02   5.6141e-02   1   Initial CI
   @MCSCF Iter   2:  -15.50110691135284   -1.4883e-02   1.3782e-02   1   APPROX
   @MCSCF Iter   3:  -15.50334998105869   -2.2431e-03   6.2876e-03   1   APPROX
   @MCSCF Iter   4:  -15.50383175864420   -4.8178e-04   3.0556e-03   1   APPROX
   @MCSCF Iter   5:  -15.50393961054233   -1.0785e-04   1.4760e-03   1   APPROX
   @MCSCF Iter   6:  -15.50396390550718   -2.4295e-05   7.1214e-04   1   APPROX
   @MCSCF Iter   7:  -15.50396940788560   -5.5024e-06   3.4415e-04   1   APPROX
   @MCSCF Iter   8:  -15.50397066792286   -1.2600e-06   1.6739e-04   1   APPROX, DIIS
   @MCSCF Iter   9:  -15.50397105202731   -3.8410e-07   1.1147e-05   1   APPROX, DIIS
   @MCSCF Iter  10:  -15.50397105396176   -1.9344e-09   6.1564e-07   1   APPROX, DIIS
   @MCSCF Iter  11:  -15.50397105396464   -2.8830e-12   9.7940e-08   1   APPROX, DIIS
   @MCSCF Iter  12:  -15.50397105396473   -8.7041e-14   1.3125e-08   1   APPROX, DIIS
   @MCSCF Iter  13:  -15.50397105396473    0.0000e+00   2.2830e-09   1   APPROX, DIIS
```

**Comment by fevangelista** [comment] 2016-08-15 20:20
York, I can confirm the problem.  At times I get `Fatal Error: Matrix::power: C_DSYEV failed`.

**Comment by jeffschriber** [comment] 2016-08-15 20:25
I also reproduce the error: `Fatal Error: Matrix::power: C_DSYEV failed`

**Comment by kannon92** [comment] 2016-08-16 02:15
York, I think this may be a problem with the number of determinants being too small.  PSI4's CI does not work if the number of determinants is too small.  If you are doing a (2,2) CAS, you should monitor the number of determinants.  There should be an error thrown if the number of determinants is less than 2.  

Also, NAN typically happens if the occupation numbers are extremely close to 0 or 2.  For a diagonal hessian update, this means that you end up dividing by zero.

**Comment by kannon92** [comment] 2016-08-16 02:24
The other thing I notice is that the tolerance you use might be too small for CASSCF.  I know that I can not always get my CASSCF code to converge to an arbitrary precision.  e_convergence is fine, but r_convergence becomes more challenging to converge to high precision.

**Comment by lcyyork** [comment] 2016-08-16 02:38
@kannon92 The number of determinants is always 2 in this case and it never falls under 2. The example I show here is near the avoided crossing region of BeH2 and the occupation numbers are 0.72 and 0.28 (ci vectors 0.85, 0.53), which I would not consider as small. The r_convergence might be too high but it does not explain the peculiar behavior of CASSCF, for examples, __run1__, __run4__, and __pk_run2__ where the first few iterations are fine and then a sudden crash.

**Comment by dgasmith** [comment] 2016-08-16 13:25
It looks like the Pade approximation to `e^(x)` is breaking down as we occasionally are getting weird eigenvalues in the `x` decomposition. Ill add an optional switch to use a Taylor series + QR decomposition/Schmidt. The problem with the Taylor series is that QR/Schmidt can push around the virtual eigenvectors quite a bit. While the rotations are still unitary with respect to energy the overall wavefunction changes considerably. QR does not push around the vectors as much; however, it can fail and while Schmidt will always succeed it can push the vectors around *alot*. Although, all of this probably hints at a more base issue-- I'm not sure what it would be. It could be something in the diagonal Hessian (as Kevin suggested), but it should be capped to avoid this.

The DPD issue with OOC JK could make sense as they both need a DPD instance. In the main Psi4 branch PK should be faster in all cases now. Ill investigate and toss up a warning if someone tries to use OOC.

Ill probably pop out a new MCSCF update either after the CMake rewrite or the inversion.

**Comment by fevangelista** [comment] 2016-08-16 15:24
@dgasmith , are you referring to the Matrix::expm() method?  C_DSYEV is only used in Matrix::power().  The only potentially problematic function in expm is C_DGETRF for LU decomposition.

**Comment by kannon92** [comment] 2016-08-16 15:56
@fevangelista, isn't C_DSYEV also used for diagonalization of H in davidson?

**Comment by kannon92** [comment] 2016-08-16 15:58
@dgasmith, The SOSCF solver already uses Taylor + Schmidt in the main psi4 branch.  I had to add a Matrix::expm() switch in my branch to bypass Schmdit.

**Comment by fevangelista** [comment] 2016-08-16 16:12
I think the preferred way to compute exp(X) is the scale and square method with Pade expansion.  This approach works for any type of matrix.  That's what is implemented in expm (I think by Rob).  However, I noticed that scaling needs to be activated with a flag by calling expm(X,true).  I am also concerned because the error is non-deterministic.

**Comment by kannon92** [comment] 2016-08-16 16:53
Yes, actually exp(X) is faster than the Schmidt (the implementation in PSI4), so that is also another benefit.  Of course, this only matters when you start doing calculations with thousands of basis functions.  Otherwise, both are very quick.  I do remember reading that scale and square method is the most well-conditioned algorithm for computing a matrix exponential.

**Comment by dgasmith** [comment] 2016-08-16 17:30
Sorry, wrote that too early in the morning. The DSYEV would happen in the DIIS which would fail due to incorrect Pade vectors. Anyhow, thats not really it. Exactly diagonalization and everything is fine. This means something is wrong in the Davidson iterations.

If you want really cheap and stable exponentiation you can always do Klein-Cayley.

**Comment by jeffschriber** [comment] 2017-01-12 17:56
Issue seems obsolete, see https://github.com/evangelistalab/forte/issues/10

**Closed by jeffschriber** 2017-01-12 17:56 UTC
