### ISSUE TITLE
'PCM Polarization Energy' randomly appear in SCF Energetics section

### ISSUE THREAD

**Issue by tyzhang1993** [evangelistalab/forte#22] opened 2017-05-26 02:42 UTC
For a simple scf job with forte parameter specified (but no need to run forte), the 'PCM Polarization Energy' randomly appears in the SCF output '=> Energetics <=' section with the statement 'Alert: EFP and PCM quantities not currently incorporated into SCF psivars.'

A sample input is

    import forte

    molecule H2O{
    0 1
    O
    H 1 1.1
    H 1 1.1 2 104.5
    }
    
    set {
      basis sto-3g
      scf_type pk
      e_convergence 10
      d_convergence 10
      r_convergence 10
    }

    set forte {
      job_type aci
    }
    energy('scf')

Sometimes the output appears as

    => Energetics <=

    Nuclear Repulsion Energy =              8.0013322999746084
    One-Electron Energy =                -120.2007809086825745
    Two-Electron Energy =                  37.2576460440522581
    PCM Polarization Energy =               0.0000000000000000
    Total Energy =                        -74.9418025646557169

    Alert: EFP and PCM quantities not currently incorporated into SCF psivars.

and sometimes just

    => Energetics <=

    Nuclear Repulsion Energy =              8.0013322999746084
    One-Electron Energy =                -120.2007809086825745
    Two-Electron Energy =                  37.2576460440522581
    Total Energy =                        -74.9418025646557169

This happens both on my mac and on the group linux cluster.
In my limited times of trial, I could not reproduce the randomness if all the lines involve forte are removed, but I noticed that the PCM lines only appear on the cluster, but never appear on my mac.
This appears as a memory issue, but I haven't found a solution.

**Comment by jeffschriber** [comment] 2017-05-26 03:04
On my mac, I see the PCM message randomly, whether the forte lines are there or commented out. Very strange. Not entirely sure how this would be a result of a memory issue, though I guess most unpredictable behavior is related to that. 

Grepping through the Psi4 tests, I notice that many of them do have the line,

    PCM Polarization Energy =               0.0000000000000000

for what it's worth.

**Comment by fevangelista** [comment] 2017-05-26 03:06
Cannot reproduce it. Could this be an issue with paths/libraries/etc.?

**Comment by tyzhang1993** [comment] 2017-05-26 03:10
I compiled without conda environment, but I compiled with the python from anaconda.
I am not sure what caused it.

**Comment by jeffschriber** [comment] 2017-05-26 03:26
Didn't use conda for my build either, but I'll try it and see if it makes a difference.

**Comment by fevangelista** [comment] 2017-06-05 20:01
I am closing this because it looks like an issue with Psi4.

**Closed by fevangelista** 2017-06-05 20:01 UTC
