### ISSUE TITLE
TypeError: unhashable type: 'forte.forte.StateInfo'

### ISSUE THREAD

**Issue by MThomasRed92** [evangelistalab/forte#212] opened 2020-12-07 12:15 UTC
Dear developers,

After much difficulty, I manage to install forte. However, all calculations fail with
`TypeError: unhashable type: 'forte.forte.StateInfo'`

Could you please let me know how to solve this?

This is the details of the installation:
GCC compiler version 7.3
Python 3.7
Intel MKL
Psi4 and ambit: the most recent version, built from source. Most of the psi4 fast tests passed.

Thanks

**Comment by lcyyork** [comment] 2020-12-07 16:06
Hi, thank you for the interests in Forte. This is likely a issue of Pybind11. As far as I tested, currently Psi4 1.4a2, Ambit 0.5.1, and Pybind11 2.5.0 are required. Currently, we have some compatibility issue with the latest Psi4 1.4a3 and Pybind11 2.6.1. May I ask for the Pybind11 version and how you installed Psi4?

**Comment by MThomasRed92** [comment] 2020-12-08 02:15
Hi, thank you for your answer. I have Pybind11 2.6.1. I uninstalled it and installed the 2.5.0 version instead. The problem is still there. I used the latest Psi4 from two days ago (https://github.com/psi4/psi4/commit/4dde4d864864bc569792ef10da0b52c09b4452d1) and installed from source. I will try to install 1.4a2. 

Thanks

**Comment by lcyyork** [comment] 2020-12-08 02:24
@MThomasRed92 Just FYI, I am on commit [766c1e7](https://github.com/psi4/psi4/commit/766c1e760db0de3b1e685fa0313cb2f2d6d9b146) of Psi4 (just before the update of Libint2).

**Comment by MThomasRed92** [comment] 2020-12-08 07:38
Thanks. I confirm that Pybind11 2.6.1 and Psi4 https://github.com/psi4/psi4/commit/766c1e760db0de3b1e685fa0313cb2f2d6d9b146 works.

**Comment by lcyyork** [comment] 2020-12-08 07:41
Awesome, thank you for testing.

**Comment by fevangelista** [comment] 2020-12-08 23:16
I am just reopening the issue because the issue is in the python API of forte. The `StateInfo` class is used in a python dict but with a recent pybind11 upgrade this does not work anymore. The solution is to define a `__hash__` function. This will be done shortly in a PR.

**Comment by fevangelista** [comment] 2020-12-09 04:54
Ok, after merging #218 there are now a couple of failing tests:
```
    DSRG-MRPT2-GRAD-FINDIFF-1
    ACI-DSRG-MRPT2-4
    DSRG-MRPT2-OPT-FINDIFF-1
Test group FCI
    FCI-EX-1
```
I will have to investigate them tomorrow.

**Comment by lcyyork** [comment] 2020-12-09 06:54
> Ok, after merging #218 there are now a couple of failing tests:
> 
> ```
>     DSRG-MRPT2-GRAD-FINDIFF-1
>     ACI-DSRG-MRPT2-4
>     DSRG-MRPT2-OPT-FINDIFF-1
> Test group FCI
>     FCI-EX-1
> ```
> 
> I will have to investigate them tomorrow. Some of these errors are of the order of 10^{-10} and so I wonder if they come from libint2 (I am running on psi4 master).

I know why the FINDIFF no longer works. It has to be related to the molecule in pymodule I changed in the last commit.

**Comment by lcyyork** [comment] 2020-12-09 08:07
@fevangelista I have fixed all the test cases. FINDIFF is a issue of molecule in pymodule. For the other two cases, I believe they failed because the integral screening in Psi4 using Libint2. I have updated in the reference values. They are in PR #216 .

**Comment by lcyyork** [comment] 2020-12-11 16:28
As PR #216 has been merged, I close this issue.

**Closed by lcyyork** 2020-12-11 16:28 UTC
